# Generated by Django 5.2.7 on 2026-01-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirelens_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofile',
            name='company_name',
            field=models.CharField(max_length=3),
        ),
    ]
