# Generated by Django 5.2.7 on 2026-01-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirelens_app', '0002_alter_hrprofile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='answer_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='hrprofile',
            name='company_name',
            field=models.CharField(max_length=150),
        ),
    ]
