# Generated by Django 5.2.7 on 2026-01-28 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirelens_app', '0003_interviewresult_answer_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillimprovementplan',
            name='analysis',
        ),
        migrations.RenameField(
            model_name='interviewresult',
            old_name='answer_text',
            new_name='candidate_answer',
        ),
        migrations.RenameField(
            model_name='interviewresult',
            old_name='conducted_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='interviewresult',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='interviewresult',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='interviewresult',
            name='job',
        ),
        migrations.RemoveField(
            model_name='interviewresult',
            name='score',
        ),
        migrations.RemoveField(
            model_name='interviewresult',
            name='skill_name',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='skill_coverage_percent',
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='ai_feedback',
            field=models.TextField(default='No feedback provided.'),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='ai_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ai_summary',
            field=models.TextField(blank=True, default='Pending Analysis...'),
        ),
        migrations.AlterField(
            model_name='companyrequirement',
            name='required_skills',
            field=models.TextField(help_text='Comma-separated skills (e.g., python, django, communication)'),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='similarity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=100)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirelens_app.resumeanalysis')),
            ],
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hirelens_app.generatedquestion'),
        ),
        migrations.DeleteModel(
            name='SkillEvaluation',
        ),
        migrations.DeleteModel(
            name='SkillImprovementPlan',
        ),
    ]
