# Generated by Django 5.2.7 on 2026-01-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirelens_app', '0004_remove_skillimprovementplan_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='extracted_skills_list',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of extracted skills'),
        ),
    ]
