# Generated by Django 5.2.7 on 2026-02-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirelens_app', '0006_interviewsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='detailed_breakdown',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of topic-wise scores'),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='interview_feedback',
            field=models.TextField(blank=True, default='', help_text='AI feedback summary'),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='interview_score',
            field=models.IntegerField(default=0, help_text='Overall AI Interview Score (0-100)'),
        ),
    ]
